import { Player, Tournament, Match } from '../../shared/types';

export const mockPlayers: Player[] = [
  {
    id: 1,
    name: 'Novak Djokovic',
    country: 'SRB',
    photoUrl: null,
    ranking: 1,
    birthdate: '1987-05-22',
    height: 188,
    weight: 77,
    plays: 'Right-Handed',
    backhand: 'Two-Handed',
    turnedPro: 2003,
  },
  {
    id: 2,
    name: 'Rafael Nadal',
    country: 'ESP',
    photoUrl: null,
    ranking: 2,
    birthdate: '1986-06-03',
    height: 185,
    weight: 85,
    plays: 'Left-Handed',
    backhand: 'Two-Handed',
    turnedPro: 2001,
  },
  {
    id: 3,
    name: 'Roger Federer',
    country: 'SUI',
    photoUrl: null,
    ranking: 3,
    birthdate: '1981-08-08',
    height: 185,
    weight: 85,
    plays: 'Right-Handed',
    backhand: 'One-Handed',
    turnedPro: 1998,
  },
  {
    id: 4,
    name: 'Carlos Alcaraz',
    country: 'ESP',
    photoUrl: null,
    ranking: 4,
    birthdate: '2003-05-05',
    height: 183,
    weight: 74,
    plays: 'Right-Handed',
    backhand: 'Two-Handed',
    turnedPro: 2018,
  },
  {
    id: 5,
    name: 'Jannik Sinner',
    country: 'ITA',
    photoUrl: null,
    ranking: 5,
    birthdate: '2001-08-16',
    height: 188,
    weight: 76,
    plays: 'Right-Handed',
    backhand: 'Two-Handed',
    turnedPro: 2018,
  },
];

export const mockTournaments: Tournament[] = [
  {
    id: 1,
    name: 'Australian Open',
    surface: 'Hard',
    category: 'Grand Slam',
    location: 'Melbourne, Australia',
    startDate: '2026-01-19',
    endDate: '2026-02-01',
  },
  {
    id: 2,
    name: 'Roland Garros',
    surface: 'Clay',
    category: 'Grand Slam',
    location: 'Paris, France',
    startDate: '2026-05-25',
    endDate: '2026-06-08',
  },
  {
    id: 3,
    name: 'Wimbledon',
    surface: 'Grass',
    category: 'Grand Slam',
    location: 'London, UK',
    startDate: '2026-06-29',
    endDate: '2026-07-12',
  },
];

export const mockMatches: Match[] = [
  {
    id: 1,
    tournamentId: 1,
    player1Id: 1,
    player2Id: 4,
    score: '6-4, 3-6, 6-3, 7-5',
    winnerId: 1,
    round: 'Final',
    date: '2026-02-01',
    statsJson: null,
  },
  {
    id: 2,
    tournamentId: 1,
    player1Id: 2,
    player2Id: 5,
    score: '7-6(4), 6-4, 6-2',
    winnerId: 5,
    round: 'Semi-Final',
    date: '2026-01-30',
    statsJson: null,
  },
  {
    id: 3,
    tournamentId: 2,
    player1Id: 3,
    player2Id: 4,
    score: '6-3, 6-7(5), 7-5, 6-4',
    winnerId: 4,
    round: 'Quarter-Final',
    date: '2026-06-04',
    statsJson: null,
  },
];
